name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install xarray pandas numpy matplotlib seaborn scipy statsmodels netCDF4

    - name: Run script
      run: python rainfall.py
